# Generated by Django 6.0.4 on 2026-05-19 10:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='categories/covers/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Anim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_japanese', models.CharField(blank=True, max_length=255)),
                ('title_english', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('synopsis', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='anims/covers/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='anims/banners/')),
                ('trailer_url', models.URLField(blank=True)),
                ('type', models.CharField(choices=[('series', 'Series'), ('movie', 'Movie'), ('ova', 'OVA'), ('ona', 'ONA'), ('special', 'Special')], default='series', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('upcoming', 'Upcoming'), ('hiatus', 'On Hiatus')], default='ongoing', max_length=20)),
                ('age_rating', models.CharField(choices=[('all', 'All Ages'), ('pg13', '13+'), ('pg16', '16+'), ('r18', '18+')], default='all', max_length=10)),
                ('studio', models.CharField(blank=True, max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_episodes', models.PositiveIntegerField(default=0)),
                ('episode_duration', models.PositiveIntegerField(default=24)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_new_release', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(blank=True, related_name='anims_by_category', to='catalog.category')),
                ('genres', models.ManyToManyField(blank=True, related_name='anims_by_genre', to='catalog.genre')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveSmallIntegerField(default=1)),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='episodes/thumbnails/')),
                ('video_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('is_filler', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('anim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='catalog.anim')),
            ],
            options={
                'ordering': ['season_number', 'episode_number'],
                'unique_together': {('anim', 'season_number', 'episode_number')},
            },
        ),
    ]
