# Generated by Django 6.0.4 on 2026-05-19 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anim',
            name='title_english',
        ),
    ]
