# Generated by Django 6.0.4 on 2026-05-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_anim_title_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='anim',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
