# Generated by Django 6.0.4 on 2026-05-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_anim_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anim',
            name='release_date',
        ),
        migrations.AddField(
            model_name='anim',
            name='release_year',
            field=models.PositiveIntegerField(blank=True, help_text='Ex: 2024', null=True, verbose_name='Année de sortie'),
        ),
    ]
