# Generated by Django 6.0.4 on 2026-05-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_anim_release_date_anim_release_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
