# Generated by Django 6.0.4 on 2026-05-22 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_category_cover_image_remove_category_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='is_visible',
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
