# Generated by Django 6.0.4 on 2026-05-22 23:05

import apps.catalog.models.episode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_category_options_remove_category_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['episode_number']},
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('anim', 'episode_number')},
        ),
        migrations.AddField(
            model_name='episode',
            name='episode_video',
            field=models.FileField(blank=True, null=True, upload_to=apps.catalog.models.episode.upload_episode_video),
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_number',
        ),
    ]
