# Generated by Django 6.0.4 on 2026-05-23 12:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_episode_options_alter_episode_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anim',
            name='is_new_release',
        ),
        migrations.RemoveField(
            model_name='anim',
            name='views_count',
        ),
        migrations.AddField(
            model_name='anim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
