# Generated by Django 6.0.4 on 2026-06-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_anim_is_new_release_remove_anim_views_count_and_more'),
        ('interactions', '0003_alter_favorite_anim_alter_favorite_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchhistory',
            options={'ordering': ['-last_watched']},
        ),
        migrations.RenameField(
            model_name='watchhistory',
            old_name='completed',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='watchhistory',
            old_name='watched_at',
            new_name='last_watched',
        ),
        migrations.RemoveField(
            model_name='watchhistory',
            name='progress',
        ),
        migrations.AddField(
            model_name='watchhistory',
            name='progress_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='episode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.episode'),
        ),
        migrations.AlterField(
            model_name='watchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.anim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('user', 'anime')},
            },
        ),
    ]
