# Generated by Django 6.0.4 on 2026-05-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='suggestedAnim',
            new_name='suggested_anim',
        ),
    ]
