# Generated by Django 6.0.4 on 2026-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0002_rename_suggestedanim_suggestion_suggested_anim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='suggested_anim',
            field=models.CharField(max_length=50),
        ),
    ]
